trigger: none

stages:
  - stage: 
    displayName: Manual Validation All Packages

    pool:
      name: azsdk-pool-mms-ubuntu-2204-general
      vmImage: ubuntu-22.04

    jobs:
      - job: BuildAllPackages
        steps:
          - template: /eng/pipelines/templates/steps/use-node-version.yml
            parameters:
              NodeVersion: 20.x

          - script: |
              node common/scripts/install-run-rush.js install
            displayName: "Install library dependencies"

          - script: |
              node common/scripts/install-run-rush.js build -t @azure/eslint-plugin-azure-sdk
              node eng/tools/rush-runner.js lint -p max
            displayName: "Build ESLint Plugin and Lint All Packages"

          - script: |
              node common/scripts/install-run-rush.js build -t @azure/eslint-plugin-azure-sdk
              node eng/tools/rush-runner.js lint -p max
            displayName: "Build All Packages"
